udo: required
dist: trusty
language: c

env:
  global:
    - WOWZA_EXPORT_PATH="/srv/docker/wowza"

services:
  - docker

install:
  - make build
  - docker container run -d --name wowza --expose 1935/tcp --expose 8086/tcp --expose 8087/tcp --expose 8088/tcp --publish 1935:1935 --publish 8086:8086 --publish 8087:8087 --publish 8088:8088 --volume /srv/docker/wowza/log/server:/usr/local/WowzaStreamingEngine/logs --entrypoint /sbin/entrypoint.sh waja/wowza-streaming-engine-linux-loadbalancer

script:
  - docker container ps | grep -q wowza-streaming-engine-linux-loadbalancer
